name: pos_krupuk
description: "POS Krupuk - Point of Sale for Krupuk Business"
publish_to: 'none'
version: 1.0.15+15

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  uuid: ^4.5.1
  fl_chart: ^0.70.2
  flutter_classic_bluetooth: ^1.0.0
  windows_printer: ^0.2.1
  image_picker: ^1.1.2
  image: ^4.9.2
  window_manager: ^0.5.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.1

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.24

msix_config:
  display_name: POS Krupuk
  publisher_display_name: Rizky
  publisher: CN=POS_KRUPUK_DEVELOPER
  identity_name: com.rizky.pos-krupuk
  msix_version: 1.0.15.0
  logo_path: assets/icon/icon.png
  capabilities: internetClient, location, bluetooth

flutter:
  uses-material-design: true
